modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/jaredlll08/Clumps/issues"

[[mods]] #mandatory
modId="clumps"
version="${file.jarVersion}"
displayName="Clumps"
displayURL="https://www.curseforge.com/minecraft/mc-mods/clumps"
credits=""
authors="Jaredlll08"
description='''
Clumps xp orbs together.
'''