modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/jaredlll08/Clumps/issues"
license="MIT"
[[mods]] #mandatory
modId="clumps"
version="${file.jarVersion}"
displayName="Clumps"
displayURL="https://www.curseforge.com/minecraft/mc-mods/clumps"
updateJSONURL="https://updates.blamejared.com/get?n=clumps&gv=1.16.5"
credits=""
authors="Jaredlll08"
description='''
Clumps xp orbs together.
'''
  [[dependencies.clumps]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
  [[dependencies.clumps]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"